version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: hospital-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-importer:
    build: ./importer
    container_name: mongo-importer
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/
    volumes:
      - ./data.json:/data/data.json:ro
    restart: "no"

volumes:
  mongo_data:
